version: '3.1'

services:
  joomla:
    image: joomla:3.9.24
    restart: always
    links:
      - joomladb:mysql
    volumes: 
      - "./:/var/www/html"
    ports:
      - '8080:80'
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: 1234

  joomladb:
    image: mysql:5.6
    ports: 
      - '3306:3306'
    volumes: 
      - "./data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - 'joomladb'
    ports:
      - '8090:80'
    environment:
      PMA_HOST: 'joomladb'
      MYSQL_ROOT_PASSWORD: 1234