name: _offline
timestamp: 1616905108
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1483060787
positions:
  search: search
  switch: switch
sections:
  header: Header
  navigation: Navigation
  above-slideshow: Above-slideshow
  slideshow: Slideshow
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-5122: 'System Messages'
  content:
    system-content-1119: 'Page Content'
  logo:
    logo-7086: 'Logo / Image'
  spacer:
    spacer-4990: Spacer
  position:
    position-position-7429: search
    position-position-2288: switch
  custom:
    custom-1215: 'Top Menu'
    custom-9149: Logo
    custom-8617: Information
    custom-7601: 'Quick Link'
    custom-6510: 'Extra Link'
    custom-4933: 'Contact Information'
  menu:
    menu-2468: Menu
  branding:
    branding-8018: Branding
  social:
    social-7114: Social
  mobile-menu:
    mobile-menu-8062: Mobile-menu
inherit:
  default:
    header: header
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    logo-7086: logo-9608
    spacer-4990: spacer-8120
    position-position-7429: position-position-8364
    custom-1215: custom-2399
    position-position-2288: position-position-2741
    menu-2468: menu-6409
    custom-9149: custom-9609
    custom-8617: custom-2410
    custom-7601: custom-6963
    custom-6510: custom-1285
    custom-4933: custom-5076
    branding-8018: branding-2819
    social-7114: social-3954
    mobile-menu-8062: mobile-menu-5697
