preset: preset1
accent:
  color-1: '#5e84ff'
  color-2: '#363a73'
  color-3: '#46a5e5'
font:
  family-default: 'family=Kanit:100,200italic,300,600,600italic'
  family-title: 'family=Kanit:100,200italic,300,600,600italic'
offcanvas:
  text-color: '#253b80'
